elasticsearch:
  replicas: 1
  image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
  es_java_opt: -Xms512m -Xmx512m
  persistence:
    storageClassName:
    storageSize: 100Gi

kibana:
  replicas: 1
  image: docker.elastic.co/kibana/kibana:7.5.0
  password: elastic
  init_index_pattern: false
  ingress:
    ingressClassName: nginx
    host: kibana.example.com
    tls:
      secret: kibana-tls
      issuer: letsencrypt-prod

fluentd:
  image: fluent/fluentd-kubernetes-daemonset:v1.15-debian-elasticsearch7-1

curator:
  schedule: "0 1 * * *"
  image: "public.ecr.aws/bitnami/elasticsearch-curator:5.8.4-debian-11-r11"
  unit_count: 15
  unit: days
  timestring: '%Y.%m.%d'
